#!/bin/bash

chown -R mysql:mysql /var/lib/mysql
mysql_install_db --user mysql > /dev/null

MYSQL_ROOT_PASSWORD="root1234"
MYSQL_DATABASE="platform"
MYSQL_USER="platform-admin"
MYSQL_PASSWORD="platform123"
MYSQLD_ARGS=${MYSQLD_ARGS:-""}
lock="/etc/lock.create_db_mysql"
tfile=`mktemp`

if [ ! -e $lock ]; then
	return 1
fi

if [ ! -f "$tfile" ]; then
    return 1
fi

cat << EOF > $tfile
CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE  CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL ON ${MYSQL_DATABASE}.* to '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
EOF

echo "---------------------"
cat $tfile
echo "---------------------"
cat $tfile | mysql -uroot -p$MYSQL_ROOT_PASSWORD
rm -f $tfile
