# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	
	# require for NFS synced folder mode
	config.vm.network :private_network, ip: '192.168.50.4'
	config.vm.provision :shell, :path => "bootstrap.sh"
	config.vm.provider "virtualbox" do |v|
		v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	end

	config.vm.box = "ubuntu/trusty64"
	config.vm.network "forwarded_port", guest: 9200, host: 9200
end
