# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	
	# require for NFS synced folder mode
	config.vm.network :private_network, ip: '192.168.50.60'

	config.vm.provider "virtualbox" do |v|
		v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		v.customize ["modifyvm", :id, "--memory", "4024"]
		v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	end

	config.vm.box = "hashicorp/precise64"

	config.vm.network "forwarded_port", guest: 80, host: 8088
	config.vm.network "forwarded_port", guest: 5432, host: 5432

	config.ssh.password = "vagrant"

	config.vm.synced_folder "/home/dien/www/reddit", "/home/vagrant/src/", nfs: true

end
